language: elixir 
install: true
script: make
addons:
  apt:
    packages:
      - cabal-install-1.18
      - ghc-7.6.3
      - python-virtualenv
      - oracle-java8-installer
    sources: [hvr-ghc]
before_install:
  - export PATH=/opt/ghc/7.6.3/bin:/opt/cabal/1.18/bin:$PATH
  - cabal update
  - wget https://github.com/manastech/crystal/releases/download/0.9.1/crystal-0.9.1-1-linux-x86_64.tar.gz -O /tmp/crystal-0.9.1-1.tar.gz
  - tar -xvf /tmp/crystal-0.9.1-1.tar.gz -C /tmp/
  - export PATH=$PATH:/tmp/crystal-0.9.1-1/bin
env:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle
