language: elixir 
install: true
jdk:
  - oraclejdk8
script: make
addons:
  apt:
    packages:
      - cabal-install-1.18
      - ghc-7.6.3
      - python-virtualenv
      - oracle-java8-installer
    sources: [hvr-ghc]
before_install:
  - export PATH=/opt/ghc/7.6.3/bin:/opt/cabal/1.18/bin:$PATH
  - cabal update
